const trendsData = [
	{ trends: 'Zverev', number: '11K' },
	{ trends: 'Nadal', number: '12K' },
	{ trends: '#RolandGarros', number: '12K' },
	{ trends: 'Ronaldo', number: '97K' },
	{ trends: 'Morata', number: '13K' },
	{ trends: 'Curry', number: '21K' },
	{ trends: 'Shakira', number: '35K' },
	{ trends: 'Gavi', number: '95K' },
	{ trends: 'Danilo', number: '11K' },
	{ trends: 'Portugal', number: '87K' },
	{ trends: 'Di Maria', number: '12K' },
	{ trends: 'Tatum', number: '11K' },
	{ trends: 'Piqu\u00e9', number: '19K' },
	{ trends: '#NBAFinals', number: '11K' },
	{ trends: 'State of Play', number: '80K' },
	{ trends: 'Post Malone', number: '33K' },
	{ trends: 'Celtics', number: '40K' },
	{ trends: 'Warriors', number: '34K' },
	{ trends: 'Sele\u00e7\u00e3o', number: '33K' },
	{ trends: 'Al Horford', number: '85K' },
	{ trends: 'wjsn', number: '14K' },
	{ trends: 'Millie Bobby Brown', number: '14K' },
	{ trends: 'The Boys', number: '18K' },
	{ trends: 'Messi', number: '17K' },
	{ trends: 'Argentina', number: '15K' },
];
