const trendsData = [
	{ trends: 'Courtois', number: '12K' },
	{ trends: 'Stranger Things', number: '52K' },
	{ trends: 'M\u00f3naco', number: '37K' },
	{ trends: 'Fabinho', number: '12K' },
	{ trends: 'Benfica', number: '25K' },
	{ trends: 'Ferrari', number: '13K' },
	{ trends: 'Celtics', number: '37K' },
	{ trends: 'Chaves', number: '13K' },
	{ trends: 'Latifi', number: '29K' },
	{ trends: 'Leclerc', number: '12K' },
	{ trends: '#UCLfinal', number: '11K' },
	{ trends: 'Butler', number: '12K' },
	{ trends: 'Warriors', number: '16K' },
	{ trends: 'Real Madrid', number: '41K' },
	{ trends: 'Liverpool', number: '55K' },
	{ trends: 'Verstappen', number: '83K' },
	{ trends: 'Perez', number: '28K' },
	{ trends: 'Valverde', number: '47K' },
	{ trends: 'Helena', number: '13K' },
	{ trends: 'Nelson', number: '21K' },
	{ trends: 'Benzema', number: '21K' },
	{ trends: 'Alcaraz', number: '15K' },
	{ trends: 'Casemiro', number: '63K' },
	{ trends: 'Mick', number: '43K' },
	{ trends: 'Cristina', number: '21K' },
	{ trends: 'Nadal', number: '70K' },
	{ trends: 'Schumacher', number: '21K' },
	{ trends: 'Charles', number: '14K' },
	{ trends: 'Alonso', number: '57K' },
	{ trends: 'Smart', number: '19K' },
	{ trends: 'Checo', number: '25K' },
	{ trends: 'Guedes', number: '12K' },
	{ trends: 'Senna', number: '11K' },
	{ trends: 'Bernardo', number: '20K' },
];
